apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: node
    spec:
      containers:
      - name: node-pod
        image: node-web-app:v1
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: PORT
          value: "80"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DATABSE
          value: postgres
        - name: POSTGRES_HOST
          value: postgres-service.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    run: node
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    run: node