FROM mhart/alpine-node:9.8.0

ARG API_WORKDIR
WORKDIR $API_WORKDIR

# Cache installation before
COPY package*.json $API_WORKDIR/
ENV NODE_ENV=production
RUN npm install --production

CMD [ "npm", "run", "prod" ]
