FROM mhart/alpine-node:9.8.0

ARG API_WORKDIR
WORKDIR $API_WORKDIR

# Cache installation before
COPY package*.json $API_WORKDIR/
ENV NODE_ENV=production
RUN npm install --production
COPY src $API_WORKDIR/src
RUN npm run build

CMD [ "npm", "run", "prod" ]
